### ISSUE TITLE
openai close text-davinci-003

### ISSUE THREAD

**Issue by marzenie** [daboynb/ChatGPT-Bypass-gui#3]
![image](https://github.com/daboynb/ChatGPT-Bypass-gui/assets/29224655/d60a8c0b-a6ce-4347-bd40-ca0f94a0a7d8)
![image](https://github.com/daboynb/ChatGPT-Bypass-gui/assets/29224655/4cae6cd7-62f6-46ae-adfb-123c26982096)

**Comment by marzenie** [comment]
![image](https://github.com/daboynb/ChatGPT-Bypass-gui/assets/29224655/e4d745cf-18dc-40be-9d79-26bac660a14e)

**Comment by daboynb** [comment]
Thank you, I'll archive this repo.
